## QUe es una Pseudoinversa de Moore

Para ciertas matrices, como es el caso de las *no cuadradas* no existe una matriz inversa. Si una matriz no tiene inversa, se dice que es **singular** 

In [67]:
import numpy as np

np.set_printoptions(suppress=True)

A= np.array([[2,3], [5,7], [11,13]])

print(A)


[[ 2  3]
 [ 5  7]
 [11 13]]


Si intentamos calcular el determinante de la matriz A, nos dara un error. Y por tanto A es *singular*

Empezaremos haciendo la descomposicion SVD, como es constumbre. 

In [68]:
U, D, V = np.linalg.svd(A)
D = np.diag(D)

print(U.shape)
print(D.shape)
print(V.shape)

(3, 3)
(2, 2)
(2, 2)


### Ejemplo

A manera de repaso, demostrar $A = UDV$

Como vimos anteriormente, es posible recuperar la matriz original A, a traves de las diferentes transformaciones lineales de U, D y V. Sin embargo necesitamos agregar una fila de ceros a la matriz diagonal, para que sus dimensiones sean 3,2

In [69]:
ceros = np.zeros((1,2))
print(ceros)

[[0. 0.]]


In [70]:
D = np.concatenate((D,ceros), axis=0)
print(D)

[[19.40321383  0.        ]
 [ 0.          0.71783924]
 [ 0.          0.        ]]


In [71]:
A_calc= U.dot(D).dot(V)
print(A_calc)

[[ 2.  3.]
 [ 5.  7.]
 [11. 13.]]


### Continuando con la Pseudo Inversa

Empezaremos por calcular la inversa de la matriz diagonal

In [72]:
U, D, V = np.linalg.svd(A)
D = np.diag(D)
print(D)



[[19.40321383  0.        ]
 [ 0.          0.71783924]]


In [73]:
inv_D = np.linalg.inv(D)
print(inv_D)

[[0.05153785 0.        ]
 [0.         1.39306957]]


Ahora, se necesita una Pseudoinversa de D: D_pse, que sera igual a la inversa de $D$ pero te tamaño 2x3. Entonces agregamos una columna de ceros al final

In [74]:
np.zeros((2,1))

D_pse = np.concatenate((inv_D, np.zeros((2,1))), axis = 1)
print(D_pse)

[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


### ¿Cual sera entonces nuestra pseudoinversa (A_pse)?

#### $A_{pse} = V^{T}·D_{pse}·U^{T}$

In [75]:
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


por suerte numpy tiene un metodo que permite calcular la pseudoinversa de una manera mas directa, y comparemos el resultado con el obtenido. Observaremos que es el mismo

In [76]:
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]


### ¿Y como comprobamos que es efectivamente la Pseudoinversa?



Recordemos una de las propiedades de la matriz inversa:

#### $A^{-1}·A = I$

In [77]:
print(A_pse.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


Esta propiedad es en realidad conmutativa, pero al ser A una matriz singular, dicha propiedad no es conmutativa, es decir:

#### $A^{-1}·A$ no es igual a $A·A^{-1}$

Al observar $A^{-1}·A = I$ vemos que hay un -0, si desactivamos la funcionalidad para que "no redondee" veremos que en realidad es un resultado aproximado, pero muy cercano, y bastante bueno

In [78]:
np.set_printoptions(suppress = False)
print(A_pse.dot(A))

[[ 1.00000000e+00 -1.77635684e-15]
 [ 4.44089210e-16  1.00000000e+00]]
