## Descomposicion de Matrices
Para este capitulo debes recordar que es la transpuesta de una matriz, sino te vas a confundir. 



**Descomponer una matriz** quiere decir encontrar dos o más matrices que me ayuden a escribir la matriz original en una forma alterna sin que deje de ser la misma matriz. Como por ejemplo escribir el numero 100 como la multiplicacion de tres numeros 25*2*2, no deja de ser el mismo numero

El concepto matematico de la descomposicion de una matriz es el de *diagonalizacion* que veremos a continuacion.


## Diagonalizacion de una matriz

Una matriz $A$ es diagonizable si existe una matriz invertible $P$ y una matriz diagonal $D$ tal que $A=PDP^{-1}$

Ejemplo: Sea la matriz $A$ del capitulo anterior, diagonalizar dicha matriz.

In [2]:
import numpy as np

A = np.array([[3,2], [4,1]])
print(A)


[[3 2]
 [4 1]]


Esta matriz tenia dos valores caracteristiccos dado por $\lambda=[5, -1]$ y dos vectores caracteristicos en este orden:
 [1, 1] y [1 -2]. Por tanto, la matriz $D$ correspondera a la Diagonal de valores caracteristicos

In [3]:
D = np.diag([5,-1])
print(D)

[[ 5  0]
 [ 0 -1]]


$P$ correspondera a los vectores propios, donde cada columna es un vector propio

In [4]:
P = np.array([[1,1], [1,-2]])
P = P.T
print(P)

[[ 1  1]
 [ 1 -2]]


$P^{-1}$ es la inversa de $P$

In [5]:
inv_P = np.linalg.inv(P)
print(inv_P)

[[ 0.66666667  0.33333333]
 [ 0.33333333 -0.33333333]]


In [6]:
A_calc = P.dot(D).dot(inv_P)
print(A_calc)

[[3. 2.]
 [4. 1.]]


Lo que acabamos de demostrar es que la matriz $A$ es diagonizable porque A = A_calc

### Caso especial, matriz simetrica

Recordemos que una matriz simetrica es aquella que $A = A^T$. Por ejemplo. Sea la matriz A

In [33]:
A = np.array([[3,2],[2,3]])
print(A)
A == A.T

[[3 2]
 [2 3]]


array([[ True,  True],
       [ True,  True]])

Observamso que A es simetrica; ahora calculamos sus autovalores y autovectores

In [29]:
autovalores, autovectores = np.linalg.eig(A)

D = np.diag(autovalores)
print(D)


[[5. 0.]
 [0. 1.]]


In [30]:
print(autovectores)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


¿Pero que otra propiedad tiene una matriz simetrica? 

Si A es simetrica, entonces $A=PDP^{T}$, y como sabemos computacionalmentes es mas conveniente calculara la transpuesta que la inversa. Asi que tener en cuenta de que nuestras matrices sean simetricas

In [34]:
P = autovectores
A_calc = P.dot(D).dot(P.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]


Acabamos de demostrar que cuando una matriz es simetrica entoncves se cumple que $A=PDP^T$

## Como descomponer una matriz que no es cuadrada

La descomposicion en autovalores y autovectores tal y como lo vimos en el capitulo anterior, solo es posible cuando la matriza es cuadrada. ¿Eso significa que no la podamos descomponer? NO, lo podemos hacer usando **valores singulares** y **vectores singulares**

En dicha descomposicion existen tres componentes o matrices: U, V, D. Donde $U$ y $D$ son ortogonales, es decir, donde cada uno de sus vectores son ortonormales; y $D$ es una matriz diagonal

- La matriz  $D$ tiene en su diagonal, todos los valores singulares
- $V$ contiene los vectores derechos singulares
- $U$ contine los vectores izqueirdos singulares

donde:

## $A = UDV$

NUMPY hace uso de la funcion SVD que permite calcular todo lo anterior. Advierto que los calculos de SVD son distintos a los hechos por el instructor

In [43]:
A = [i for i in range(1,7)]
A = np.array(A).reshape(2,3)

print(A)

[[1 2 3]
 [4 5 6]]


In [40]:
U, D, V = np.linalg.svd(A)
print(U)


[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]


In [47]:
print(D)


[9.508032   0.77286964]


In [56]:
D = np.diag(D)
print(D)


[[9.508032   0.        ]
 [0.         0.77286964]]


In [49]:
print(V)

[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


Demostremos que $A=UDV$ Pero antes tengamos en cuenta las propiedades de las matrices, porque si no va a generar un error en el codigo


In [60]:
print(U.shape)
print(D.shape)
print(V.shape)

(2, 2)
(2, 2)
(3, 3)


Al multiplicar U por D dara como resultado una matriz 2x2 que no se podra multiplicar por una matriz 3x3. Entonces el truco es añadir una columna de zeros a la matriz diagonal.

In [77]:
ceros = np.zeros((2,1))
print(ceros)
print(ceros.shape)


[[0.]
 [0.]]
(2, 1)


In [79]:
D = np.concatenate((D,ceros), axis=1)
print(D)

[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]


AHora si podemos realizar la operacion completa

In [89]:
A_calc = U.dot(D).dot(V)
print(A_calc)

[[1. 2. 3.]
 [4. 5. 6.]]


Como hemos visto la matriz calculada es igual a la matriz original